In [47]:
# https://wikidocs.net/37406 

import torch
import torch.nn as nn
import torch.optim as optim

In [48]:
# 신경망 정의
class MyNeuralNetwork(nn.Module):
    def __init__(self):
        super(MyNeuralNetwork, self).__init__()
        layer_1=nn.Linear(in_features=2, out_features=2, bias=False)
        weight_1 = torch.tensor([[.3,.25],[.4, .35]])
        
        layer_1.weight = nn.Parameter(weight_1)
        self.layer1 = nn.Sequential(
            layer_1,
            nn.Sigmoid()
        )
        
        layer_2 = nn.Linear(in_features=2, out_features=2, bias=False)
        weight_2 = torch.tensor([[.45, .4],[.7, .6]])
        
        layer_2.weight = nn.Parameter(weight_2)
        self.layer2 = nn.Sequential(
            layer_2,
            nn.Sigmoid()
        )
    
    def forward(self, input):
        output = self.layer1(input)
        output = self.layer2(output)
        
        return output
    
model = MyNeuralNetwork().to("cpu")
print(model)

MyNeuralNetwork(
  (layer1): Sequential(
    (0): Linear(in_features=2, out_features=2, bias=False)
    (1): Sigmoid()
  )
  (layer2): Sequential(
    (0): Linear(in_features=2, out_features=2, bias=False)
    (1): Sigmoid()
  )
)


In [49]:
# 순전파 정의 및 구현
input = torch.tensor([0.1,0.2]).reshape(1,-1)
target = torch.tensor([0.4,0.6]).reshape(1,-1)

out = model(input)
print(f"output value : {out}")

criterion = nn.MSELoss()
loss = criterion(out, target)
print(f"loss value : {loss}")


output value : tensor([[0.6094, 0.6638]], grad_fn=<SigmoidBackward0>)
loss value : 0.02397189661860466


In [45]:
# 연전파 시켜보기 -> 경사하강법 역사 정리

model.zero_grad() 
print('↓ layer1.weight before backward propagation ↓')
print(model._modules['layer1']._modules['0'].weight)
print(model._modules['layer2']._modules['0'].weight)
print()

loss.backward() # where can I put the learning late in back propagation.
print('↓ layer1.weight after backward propagation ↓')
print(model._modules['layer1']._modules['0'].weight)
print(model._modules['layer2']._modules['0'].weight)

↓ layer1.weight before backward propagation ↓
Parameter containing:
tensor([[0.3000, 0.2500],
        [0.4000, 0.3500]], requires_grad=True)
Parameter containing:
tensor([[0.4500, 0.4000],
        [0.7000, 0.6000]], requires_grad=True)

↓ layer1.weight after backward propagation ↓
Parameter containing:
tensor([[0.3000, 0.2500],
        [0.4000, 0.3500]], requires_grad=True)
Parameter containing:
tensor([[0.4500, 0.4000],
        [0.7000, 0.6000]], requires_grad=True)


In [ ]:
optimizer = optim.SGD(model.parameters(), lr=0.5)
loss = nn.MSELoss()

epochs = 1
for epoch in range(epochs):
    optimizer.zero_grad()
    
    estimated_y = model(input)
    loss = loss(target, estimated_y)
    loss.backward()
    optimizer.step()